### PR TITLE
Add Vue example.

### PR DESCRIPTION
**Pull request by sustained**
See #22.

### CODE REVIEW

**Comment by sustained** [comment]
The only thing that changed apart from React > Vue is I added `overflow-x: hidden` on `.grid` to prevent the scrollbar-when-animating issue - perhaps you could add that to your pen as well. :upside_down_face:

**Comment by aholachek** [comment]
Nice, I will take a look and then hopefully merge this later today.

**Comment by hacknug** [comment]
Adding `overflow: hidden;` makes the browser hide part of the cards when transitioning. Should be removed imho. Everything else looks good 👍

**Comment by aholachek** [comment]
Looks great! Thank you.

**Comment by sustained** [comment]
@hacknug Hmm, well it surely looks a lot better than horizontal scrollbars appearing and disappearing whenever an animation is triggered?

---

Okay, thanks! :relaxed:

**Comment by hacknug** [comment]
They don't show on my iMac so… 🤷‍♂ haha

**Comment by sustained** [comment]
You can see it here: https://www.youtube.com/watch?v=P2eBJdoiFcM&feature=youtu.be

Anywho this discussion probably doesn't belong in a merged PR - maybe you could create an issue if you really want? :sweat_smile:

**Pull request merged**
